languageCode: "en-us"
baseUrl: "/"
title: "trentjones.dev"
theme: "anubis"
paginate: 10
googleAnalytics: UA-123-45
enableRobotsTXT: true
disqusShortname: yourdiscussshortname


menu:
  main:
  - identifier: archive
    name: Posts
    title: Posts
    url: /posts/
    weight: 0

params:
  author: "Trent Jones"
  description: ""
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true

markup:
  goldmark:
    renderer:
      unsafe: true